### ISSUE TITLE
Creating severities randomly fails

### ISSUE THREAD

**Issue by dsolsona** [firehydrant/terraform-provider-firehydrant#1]
Hi,

I'm testing the terraform provider for FireHydrant and I'm seeing a weird behaviour when creating severities.  

I have a TF file that creates five different severities, from SEV1 to SEV5. When I ran terraform two severities were created and 3 failed with `Error: Could not create severity SEV3`. 

On the next run one extra severity was created and two more failed, and the remaining two needed an extra run to be created. 

So three total terraform runs to create five severities. 

This seems to consistently happening, if I delete all severities again I'll get the same errors. 

Running in debug mode isn't throwing anything interesting.

The code I'm using 

```
locals {
  severities = [ "SEV0","SEV1","SEV2","SEV3","SEV4","SEV5",]
}
resource "firehydrant_severity" "sev" {
  for_each = toset(local.severities)

  slug        = each.key
}

```

And the output on the first run

```
tf-apply
firehydrant_severity.sev["SEV5"]: Creating...
firehydrant_environment.environments["Production"]: Creating...
firehydrant_severity.sev["SEV4"]: Creating...
firehydrant_severity.sev["SEV2"]: Creating...
firehydrant_severity.sev["SEV1"]: Creating...
firehydrant_severity.sev["SEV3"]: Creating...
firehydrant_severity.sev["SEV0"]: Creating...
firehydrant_environment.environments["Integration"]: Creating...
firehydrant_environment.environments["Staging"]: Creating...
firehydrant_severity.sev["SEV5"]: Creation complete after 1s [id=SEV5]
firehydrant_environment.environments["Integration"]: Creation complete after 1s [id=9a769e60-7057-4c5f-b652-ba615cc0d99d]
firehydrant_environment.environments["Production"]: Creation complete after 1s [id=a515cab0-9ff6-47a2-95ea-d10a8a7cfad7]
firehydrant_environment.environments["Staging"]: Creation complete after 1s [id=e70cec7b-66a3-4f4a-a324-f85537e54c01]
firehydrant_severity.sev["SEV3"]: Creation complete after 2s [id=SEV3]
firehydrant_severity.sev["SEV1"]: Creation complete after 2s [id=SEV1]
firehydrant_severity.sev["SEV0"]: Creation complete after 2s [id=SEV0]

Error: Could not create severity SEV4



Error: Could not create severity SEV2


```

**Comment by bobbytables** [comment]
Hey @dsolsona, sorry for a very late reply here. We've identified this problem as an issue with our API and will ship a fix soon. Thanks for reporting it.

**Comment by marceloboeira** [comment]
Any updates here @bobbytables? just curious

**Comment by lafentres** [comment]
@marceloboeira @dsolsona This has been fixed in the API! 🎉 I also tested creating and deleting multiple severities with the provider and everything worked as expected. I used the following config, as SEV1-SEV5 exist by default in FireHydrant now.
```
locals {
  severities = [ "TESTSEV0","TESTSEV1","TESTSEV2","TESTSEV3","TESTSEV4","TESTSEV5",]
}
resource "firehydrant_severity" "sev" {
  for_each = toset(local.severities)

  slug        = each.key
}
```

I'm going to close this issue but if you have any problems, please open a new issue and we'll be happy to take a look. 

Thanks again for reporting this issue :]
