### ISSUE TITLE
Request: firehydrant_teams data source

### ISSUE THREAD

**Issue by splittingred** [firehydrant/terraform-provider-firehydrant#108]
### Use-cases

Hello! Right now FireHydrant does not allow for team data sources, meaning that the team resources _must_ be created in the same terraform repository as the service declarations. It also means that teams _must_ be managed (or at least imported) into TF state, which would complicate future possible integrations with SAML/SCIM for managing FireHydrant teams in an external identity provider.

It'd be nice to have a `firehydrant_teams` + `firehydrant_team` [data sources](https://registry.terraform.io/providers/firehydrant/firehydrant/latest/docs/data-sources/functionality), which would allow querying for said data sources in a TF repository without having to explicitly manage them there.

We personally want services to have their own terraform folders in their Git repository, allowing federation of service-related content (such as firehydrant services, etc), so being able to manage "central" or "global" content in a separate TF repo is paramount to us. For this to occur, we would need data sources for centralized content - we have this now already with `firehydrant_environment`, `firehydrant_severity`, `firehydrant_runbook`, etc, but no team support. This limits our ability to manage FireHydrant services in a federated fashion.

Thanks!

**Comment by mohamed-haidara-cko** [comment]
+ 1 on this. Same need. We are using an external data source to fetch our teams at the moment (which is a hack)

**Comment by sofuture** [comment]
Thanks for your contribution @splittingred , releasing as 0.3.4 shortly
