### ISSUE TITLE
firehydrant_service: Add support for external_resources and auto_add_responding_team

### ISSUE THREAD

**Issue by mohamed-haidara-cko** [firehydrant/terraform-provider-firehydrant#120]
### Use-cases

- We would like to use this provider to link our FireHydrant services to external resources such as github or pager_duty. 
- Same need to support the flag `auto_add_responding_team`

Note that these attributes are [already supported by the API](https://developers.firehydrant.com/#/operations/postV1Services). They need to be implemented in the provider. 

### Attempted Solutions

After creating a service via the provider, we are using the UI to make the link between PagerDuty and FireHydrant.

### Proposal

Add the missing attributes in the `firehydrant_service` resource. 

### References

Nothing to add

**Comment by aelhamahmy-twilio** [comment]
+1

**Comment by bobbytables** [comment]
Hi @aelhamahmy-twilio and @mohamed-haidara-cko ! Thanks for opening and endorsing this issue on our provider.

For the `auto_add_responding_team` item – From what I can tell, the provider already supports this for the `firehydrant_service` but we made a mistake in not cutting a new tag for the provider (It's still on 0.3.1).

As for the external resources, I'll look into that and see what I can do and if I can get that quickly going, we'll cut a new release with both, if it takes a bit longer, I'll cut a tag to make sure you get some of the requested functionality.

**Comment by mohamed-haidara-cko** [comment]
Hi @bobbytables thanks a lot for considering this :-)

**Comment by aelhamahmy-twilio** [comment]
Hi @bobbytables,  I just noticed that this issue mentions adding external_resources for just FireHydrant Services, would it be possible to add this for FireHydrant Functionalities as well or should this be tracked in a different GitHub issue?

**Comment by sofuture** [comment]
Resolved in #122
