### ISSUE TITLE
firehydrant_team "id" parameter is missing

### ISSUE THREAD

**Issue by tfhartmann** [firehydrant/terraform-provider-firehydrant#13]
According to the [docs](https://registry.terraform.io/providers/firehydrant/firehydrant/latest/docs/resources/team) I should be able to optionally pass in the team ID, however when I attempt to pass that parameter in,  I get an invalid or unknown key error 😢  removing the `id` parameter clears the error.  I'm not sure if this was a documentation error, or missing functionality :) 

I'm using Terraform Version : 1.0.9  and Provider version : 0.1.3 

```Hcl
resource "firehydrant_team" "is" {
  for_each    = var.teams
  name        = title(each.key)
  description = each.value
  id          = each.key
}
```

error: 

```Shell
╷
│ Error: Invalid or unknown key
│ 
│   with firehydrant_team.is,
│   on main.tf line 30, in resource "firehydrant_team" "is":
│   30:   id          = each.key
│ 
```

**Comment by bobbytables** [comment]
Hey @tfhartmann !

Looking at the examples you provided, are you attempting to create teams with a specific ID in FireHydrant? Looking at the docs I think what it's (trying) to say is that an ID is available on the resource's state when the team is created.

The FireHydrant API doesn't allow setting custom IDs for resources, so I'm going to look into why there's an ID attribute in the resource here.

**Comment by lafentres** [comment]
Hi there @tfhartmann!

@bobbytables is correct, ID is the ID of the team. That's generated by FireHydrant and isn't an attribute you can pass in. I've updated the docs to make this clearer here: https://github.com/firehydrant/terraform-provider-firehydrant/pull/26
