### ISSUE TITLE
Importing Default runbook forces attachment_rule to the default

### ISSUE THREAD

**Issue by kneemaa** [firehydrant/terraform-provider-firehydrant#130]
### Terraform Version

```
terraform version 
Terraform v1.3.9
on darwin_amd64
```

### Terraform Configuration Files

```terraform
resource "firehydrant_runbook" "default" {
  name                    = "Default Runbook"
  attachment_rule = null

  steps {}
  steps {}
  steps {}
}
```

### Expected Behavior

```terraform
No changes. Your infrastructure matches the configuration.
```

### Actual Behavior

```terraform
+ attachment_rule = jsonencode(
  {
    + logic     = {
        + manually = [
            + {
                + var = "when_invoked"
              },
          ]
      }
    + user_data = {}
  }
```

### Steps to Reproduce

1. Have an existing Runbook - I experienced this on the Default Runbook
2. Configure the terraform and set `attachment_rule = null` - because a default is being forced when unset
3. Import the runbook into terraform
`terraform import firehydrant_runbook.default <runbook-id>`
4. Plan Changes
5. See that the `attachment_rule` wants to switch back to manual
6. Run Apply 
7. Go to FireHydrant UI -> Runbooks -> Default Runbook -> Runbook will no longer be Automatic
8. Manually edit the Default Runbook and unset the manual attachment rule
9. Run Plan and see no `No changes. Your infrastructure matches the configuration.`

### Additional Context

It should be noted that when I cloned the original Default Runbook, this issue did not occur. This leads me to believe that this will happen to "legacy" runbooks.

**Comment by sofuture** [comment]
To keep default automatic attachment behavior, you can specify

```
attachment_rule = jsonencode({})
```

I believe this fixes your use case, can you confirm @kneemaa ? I'll see if there are docs that need updating.

**Comment by kneemaa** [comment]
> To keep default automatic attachment behavior, you can specify
> 
> 
> 
> ```
> 
> attachment_rule = jsonencode({})
> 
> ```
> 
> 
> 
> I believe this fixes your use case, can you confirm @kneemaa ? I'll see if there are docs that need updating.

@sofuture that seems to have worked
