### ISSUE TITLE
Documentation shows incorrect field name for toggling automatic alerting on services

### ISSUE THREAD

**Issue by LeviHassel** [firehydrant/terraform-provider-firehydrant#61]
In the documentation, it shows that `add_on_alert` is what's used to control automatic alerting on services. However, terraform plans with that field run into errors. After inspecting the source code, I saw that the correct field is called `alert_on_add` and my plans completed successfully once I switched to that.

**Comment by lafentres** [comment]
Hello there! Thanks for reporting this. I've open a PR to fix this: #62
