### ISSUE TITLE
Runbook cannot be created with empty step

### ISSUE THREAD

**Issue by chrisyao2022** [firehydrant/terraform-provider-firehydrant#68]
Provider [documentation](https://registry.terraform.io/providers/firehydrant/firehydrant/latest/docs/resources/runbook#optional) must be updated, as step is mandatory instead of optional during runbook creation

![image](https://user-images.githubusercontent.com/104439788/176194353-2c505710-0b87-4330-b0da-177e3315a135.png)

**Comment by lafentres** [comment]
Thanks for reporting this @chrisyao2022! I've just merged a fix for it which will be released in 0.3.0
